//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestarauntDeliveryCook.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Meal
    {
        public Nullable<int> MealID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int ID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Meal Meal { get; set; }
        public virtual Order Order { get; set; }
    }
}
